AWSTemplateFormatVersion: '2010-09-09'

Description: Deploys 2 instances with the same configuration, from the specified AMI.
Outputs:
  InstanceIds:
    Description: InstanceIds of the instances created
    Value: !Join [",", [!Ref Instance1, !Ref Instance2]]
Parameters:
  InstanceProfileName:
    Description: Name of the instance profile to attach
    Type: String
  KeyPairName:
    Description: Keypair for the instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription : Must be the name of an existing EC2 Keypair
  InstanceType:
    Description: Amazon EC2 Instance Type
    Type: String
    Default: t2.medium
    AllowedValues: [
      t2.micro,
      t2.medium, 
      t2.large
    ]
  AmiId:
    Description: Ami Id for Linux
    Type: String
  VpcId:
    Description: VPC id for the security group
    Type: String
Resources:
  ManagedInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ssm.amazonaws.com
            - ec2.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
      Path: "/"
  ManagedInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
      - !Ref ManagedInstanceRole
      InstanceProfileName: !Ref InstanceProfileName
    DependsOn: ManagedInstanceRole
  SSHAccessGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: Enable SSH access via port 22
      GroupName: SSHAccess
      SecurityGroupIngress:
        CidrIp: 0.0.0.0/0
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22
  Instance1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref AmiId
      KeyName: !Ref KeyPairName
      IamInstanceProfile: !Ref InstanceProfileName
      SecurityGroupIds: [!GetAtt SSHAccessGroup.GroupId]
      Tags:
      - Key: Name
        Value: HRAppLinux
      - Key: HRAppEnvironment
        Value: Production
      - Key: Environment
        Value: Production
    DependsOn: 
      - SSHAccessGroup 
      - ManagedInstanceProfile
  Instance2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref AmiId
      KeyName: !Ref KeyPairName
      IamInstanceProfile: !Ref InstanceProfileName
      SecurityGroupIds: [!GetAtt SSHAccessGroup.GroupId]
      Tags:
      - Key: Name
        Value: HRAppLinux
      - Key: HRAppEnvironment
        Value: Production
      - Key: Environment
        Value: Production
    DependsOn: 
      - SSHAccessGroup
      - ManagedInstanceProfile
  
